FROM golang:1.17 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

#run go binary  in alpine
# Run the Go Binary in Alpine.
FROM alpine:3.15
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_sales-api /service /service
WORKDIR /service
CMD ["./service-3"] 

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
    org.opencontainers.image.title="sales-api" \
    org.opencontainers.image.authors="Facundo Diaz <facu.dev@gmail.com>" \
    org.opencontainers.image.source="https://github.com/fd1az/service-3" \
    org.opencontainers.image.revision="${BUILD_REF}" \
    org.opencontainers.image.vendor="Fd1az"

